### ISSUE TITLE
Error on compiling.  2 variables not declared.  Arduino 1.8.3

### ISSUE THREAD

**Issue by ML-Weiss** [CoffeeTronics/Arduino-PID-Controller-for-Espresso-V2.0#2]
Arduino_PID_for_Espresso_v2_0:87: error: 'menuUsed' was not declared in this scope

 MenuBackend menu = MenuBackend(menuUsed,menuChanged);

                                ^

Arduino_PID_for_Espresso_v2_0:87: error: 'menuChanged' was not declared in this scope

 MenuBackend menu = MenuBackend(menuUsed,menuChanged);

**Comment by ML-Weiss** [comment]
Figured out the problem:

Add the following before MenuBackend(menuUseEvent,menuChangeEvent);

static void menuChangeEvent(MenuChangeEvent changed);
static void menuUseEvent(MenuUseEvent used);

**Comment by Norrox** [comment]
@ML-Weiss 
I changed what you said above but now we are getting these errors :S


> C:\Users\UK\AppData\Local\Temp\cc1UkDbY.ltrans2.ltrans.o: In function `__base_ctor ':
>  
> C:\Program Files (x86)\Arduino\libraries\MenuBackend/MenuBackend.h:151: undefined reference to `menuChangeEvent(MenuChangeEvent)'
>  
> C:\Program Files (x86)\Arduino\libraries\MenuBackend/MenuBackend.h:151: undefined reference to `menuChangeEvent(MenuChangeEvent)'
>  
> C:\Program Files (x86)\Arduino\libraries\MenuBackend/MenuBackend.h:152: undefined reference to `menuUseEvent(MenuUseEvent)'
>  
> C:\Program Files (x86)\Arduino\libraries\MenuBackend/MenuBackend.h:152: undefined reference to `menuUseEvent(MenuUseEvent)'
>  
> collect2.exe: error: ld returned 1 exit status
>  
> exit status 1
> Error compiling for board Arduino/Genuino Uno.
> 
The rows in the audrino is like this 
```
static void menuChangeEvent(MenuChangeEvent changed);
static void menuUseEvent(MenuUseEvent used);

//Menu variables
MenuBackend menu = MenuBackend(menuUseEvent,menuChangeEvent);
```

**Comment by CoffeeTronics** [comment]
I found that using function prototypes fixed that problem.

**Comment by Arduino-n00b** [comment]
Hello folks.

I ran into this project and I think it is great.

I am having one issue after looking over the code and made the following corrections.

Add the following before MenuBackend(menuUseEvent,menuChangeEvent);

static void menuChangeEvent(MenuChangeEvent changed);
static void menuUseEvent(MenuUseEvent used);

After that it seemed to work aside from this error code:

Error compiling for board Arduino/Genuino Uno.

What am I doing wrong?

P.S. I want to use an SPI interface for the LCD but only after I can get it to compile with my IDE for my Uno.

I will share my alterations to this project and thank you in advance.

**Comment by hikerlt1951** [comment]
Trying to compile this version V2.0, and get errors ( attached below). I am using the Jameco PID Temperature Controller kit part # 2190178, running arduino IDE 1.8.13 on windows 10 PC.

QUESTION - does anyone have a newer version that works, from the "Arduino PID for Espresso V2.0 by Ross Satchell 2013" ??

**Errors found when compiling V2.0:**

Arduino: 1.8.13 (Windows 10), Board: "Arduino Uno"

sketch_jul10b:87:32: error: 'menuUsed' was not declared in this scope

 MenuBackend menu = MenuBackend(menuUsed,menuChanged);

                                ^~~~~~~~

C:\Users\LT\AppData\Local\Temp\arduino_modified_sketch_182912\sketch_jul10b.ino:87:32: note: suggested alternative: 'menu'

 MenuBackend menu = MenuBackend(menuUsed,menuChanged);

                                ^~~~~~~~

                                menu

sketch_jul10b:87:41: error: 'menuChanged' was not declared in this scope

 MenuBackend menu = MenuBackend(menuUsed,menuChanged);

                                         ^~~~~~~~~~~

C:\Users\LT\AppData\Local\Temp\arduino_modified_sketch_182912\sketch_jul10b.ino: In function 'void setup()':

sketch_jul10b:679:6: error: redefinition of 'void setup()'

 void setup() {

      ^~~~~

C:\Users\LT\AppData\Local\Temp\arduino_modified_sketch_182912\sketch_jul10b.ino:132:6: note: 'void setup()' previously defined here

 void setup() {

      ^~~~~

C:\Users\LT\AppData\Local\Temp\arduino_modified_sketch_182912\sketch_jul10b.ino: In function 'void loop()':

sketch_jul10b:684:6: error: redefinition of 'void loop()'

 void loop() {

      ^~~~

C:\Users\LT\AppData\Local\Temp\arduino_modified_sketch_182912\sketch_jul10b.ino:171:6: note: 'void loop()' previously defined here

 void loop() {

      ^~~~

Multiple libraries were found for "Wire.h"

 Used: C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\Wire

 Not used: C:\Program Files (x86)\Arduino\libraries\Wire

exit status 1

'menuUsed' was not declared in this scope



This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by hikerlt1951** [comment]
Thank You !

The fix in the program that you did works great !
